### ISSUE TITLE
How to run the example app?

### ISSUE THREAD

**Issue by alloy** [mmslate/react-native-quiltview#1]
Hey, this looks really great, the source is teaching me a lot about how to use UICollectionView.

However, I’m having a hard time bootstrapping and running the example application. Could you maybe provide some steps to get up and running from a fresh clone in your README?

**Comment by alloy** [comment]
To be clear, I was able to build the app after adding all the dependency libraries as target dependencies of the example app target, but it’s also missing the pull to refresh code, so I just commented that out. (You might want to look at using CocoaPods to setup all these Xcode dependencies.)

But once the app ran, I got errors from the JS logic that I was unable to easily figure out.

**Comment by linyize** [comment]
@alloy We have updated the demo to support react native 0.20.0  and fixed the issue you mentioned. Please try again.

**Comment by alloy** [comment]
Thanks for the fix, I’m able to run the example now!
